title: Victor Toh Wei Jie # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Summary and Skills</b>
  <hr { display: block; margin-before: 0.5em; margin-after: 0.5em; margin-start: auto; margin-end: auto; overflow: hidden; border-style: inset; border-width: 1px;}>
  Meticulous individual passionate in the data analytics and BI industry. Key skills include Python Pandas, SQL and Power BI.
  <br><br>
  <b>Certifications</b>
  <hr>
  <a href="https://www.coursera.org/account/accomplishments/specialization/certificate/XFDXD34NHQQA">Google Data Analytics Certification on Coursera</a>
  <br><br>
  <hr>
  <a href="https://www.linkedin.com/in/victor-toh-wei-jie-0812ab15a/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
