title: Victor Toh Wei Jie # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  This portfolio showcases all my projects in Data Analytics/Business Intelligence.
  <br><br>
  Skills: Python (Pandas)
  <br><br>
  Certifications: Google Data Analytics Certification on Coursera
  <br><br>
  <a href="https://www.linkedin.com/in/victor-toh-wei-jie-0812ab15a/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
