title: Victor Toh Wei Jie # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <b>About Me</b>
  <hr>
  Hello! I am Victor Toh and particularly enjoy working with data and numbers, and finding insights of data through visualisations.
  My key skills include Python Pandas, SQL and Power BI.
  <br>
  Here, you can find a collection of projects I have worked on related to Data Analytics and Business Intelligence.
  <br><br>
  <hr>
  <a href="https://www.linkedin.com/in/victor-toh-wei-jie-0812ab15a/" target="_blank">Contact me on LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
